---
- name: Install RPM-Key for Logstash
  rpm_key: state=present key=http://packages.elasticsearch.org/GPG-KEY-elasticsearch

- name: logstash-repo install
  copy: src=logstash.repo
        dest=/etc/yum.repos.d/
        owner=root group=root mode=0644

- name: ensure logstash is at the latest version
  yum: pkg=logstash state=latest
  notify:
    - restart logstash
