---
- name: Install Webserver
  yum: pkg=httpd state=latest
  notify: restart httpd

- name: Install mod-ssl
  yum: pkg=mod_ssl state=latest
  notify: restart httpd

- name: Copy basic httpd configuration
  template: src=etc/httpd/conf/httpd.conf.j2 dest=/etc/httpd/conf/httpd.conf
  notify:
  - restart httpd

- name: Remove default files
  file: path=/etc/httpd/conf.d/{{ item }} state=absent
  with_items:
    - 'README'
    - 'ssl.conf'
    - 'welcome.conf'
  notify:
  - restart httpd

- name: Create certificate directory
  file: path=/etc/httpd/ssl state=directory

- name: create self-signed SSL cert
  command: openssl req -new -nodes -x509 -subj "/C=DE/ST=NRW/L=Duesseldorf/O=IT/CN={{ ansible_fqdn }}" -days 3650 -keyout /etc/httpd/ssl/server.key -out /etc/httpd/ssl/server.crt -extensions v3_ca creates=/etc/httpd/ssl/server.crt
  notify: 
  - restart httpd
